// <auto-generated />
using System;
using IchniOnline.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IchniOnline.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421021606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IchniOnline.Server.Entities.BeatmapDb", b =>
                {
                    b.Property<Guid>("BeatmapId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<string>("Composer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("composer");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<string>("IllustrateUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("illustrate_url");

                    b.Property<string>("Illustrator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("illustrator");

                    b.Property<string>("LevelColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level_color");

                    b.Property<string>("LevelDesigner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level_designer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("notes");

                    b.Property<long>("ScheduledReleaseTime")
                        .HasColumnType("bigint")
                        .HasColumnName("release_time");

                    b.Property<string>("SongName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("song_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("BeatmapId");

                    b.ToTable("beatmap", (string)null);
                });

            modelBuilder.Entity("IchniOnline.Server.Entities.GameUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("PasswordHashed")
                        .HasColumnType("text")
                        .HasColumnName("password_hashed");

                    b.Property<int>("Permission")
                        .HasColumnType("integer")
                        .HasColumnName("permission");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("game_user", (string)null);
                });

            modelBuilder.Entity("IchniOnline.Server.Entities.PlayData", b =>
                {
                    b.Property<Guid>("PlayDataId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AchieveTime")
                        .HasColumnType("bigint")
                        .HasColumnName("time");

                    b.Property<long>("BadCount")
                        .HasColumnType("bigint")
                        .HasColumnName("bad_count");

                    b.Property<Guid>("BeatmapId")
                        .HasColumnType("uuid")
                        .HasColumnName("beatmap_id");

                    b.Property<long>("GoodCount")
                        .HasColumnType("bigint")
                        .HasColumnName("good_count");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<long>("MaxCombo")
                        .HasColumnType("bigint")
                        .HasColumnName("max_combo");

                    b.Property<long>("MissCount")
                        .HasColumnType("bigint")
                        .HasColumnName("miss_count");

                    b.Property<long>("PerfectCount")
                        .HasColumnType("bigint")
                        .HasColumnName("perfect_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("PlayDataId");

                    b.HasIndex("BeatmapId");

                    b.HasIndex("UserId");

                    b.ToTable("play_data", (string)null);
                });

            modelBuilder.Entity("IchniOnline.Server.Entities.ThirdParty.TapTapOauth", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BindUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TapTapOpenId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taptap_open_id");

                    b.Property<string>("TapTapUnionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("taptap_union_id");

                    b.HasKey("Id");

                    b.ToTable("taptap_inter_auth", (string)null);
                });

            modelBuilder.Entity("IchniOnline.Server.Entities.PlayData", b =>
                {
                    b.HasOne("IchniOnline.Server.Entities.BeatmapDb", "Beatmap")
                        .WithMany()
                        .HasForeignKey("BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IchniOnline.Server.Entities.GameUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beatmap");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
